### ISSUE TITLE
Sharing and uploading the models

### ISSUE THREAD

**Issue by MohammedAlsubaie** [jerryjee120/Neural-Network#12]
If we just can share the actual models rather then pictures or code, that would be really great 
Also if we can upload or models so we can get them later if we delete the app and install it again.

**Comment by MohammedAlsubaie** [comment]
I already got this app and paid for it twice one for my Android tablet and another for my mac and I want to share the models between my devices. But honestly it is really awesome

**Comment by jerryjee120** [comment]
Thank you very much for your support!
Your proposal is great and we will support the import and export of model files in the future. Stay tuned!
