### ISSUE TITLE
怎么导入模型？

### ISSUE THREAD

**Issue by temporalu** [jerryjee120/Neural-Network#16]
我在模型页面点导入按钮，尝试把 tensorflow 官方库的 inception_v4.py 模型导进去，但是好像不行，文档里好像也没找到说支持导入哪类文件。
我导入的文件可以在这里下载：https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v4.py
![CleanShot 2024-05-26 at 10 34 21@2x](https://github.com/jerryjee120/Neural-Network/assets/122422616/157cffb8-f096-415b-be44-a79eef65cca2)

**Comment by jerryjee120** [comment]
您好！

这里只支持从本App里的导出的模型（json格式），并不支持导入模型，如python文件
设计这个功能的本意是支持模型的分享，如把模型导入出来，分享给别人，或者导入到电脑版本中。

祝好！
