### ISSUE TITLE
Locked buttons in the playground 

### ISSUE THREAD

**Issue by nytschgeusen** [jerryjee120/Neural-Network#2]
Hi,

I love the idea and concept of the Neural Network app which has convinced me. For this reason, I invested the money into the VIP unlocked version. Unfortunately there are still some unlocked  buttons in the playground (see the screenshot  below). I don’t know whether this is a bug in the code or if I have understood something wrong.

Please, can you check it?

Best Christoph

![24102D2E-1C4D-4B4C-8F5F-DBBD9972656C](https://user-images.githubusercontent.com/6739820/124355194-3e6f4880-dc10-11eb-91d0-4cb7834038ea.png)

![FBACD3B2-5330-4EC7-833D-066673D9C2E5](https://user-images.githubusercontent.com/6739820/124355239-6c548d00-dc10-11eb-889e-ca53f8d1ca2b.png)
![AB3E0E64-D25A-4CF2-A9DF-4D55F6365621](https://user-images.githubusercontent.com/6739820/124355242-6eb6e700-dc10-11eb-8a50-0fc09a72ff58.png)

**Comment by nytschgeusen** [comment]
Sorry, I mean some  **locked** buttons in the playground …

**Comment by jerryjee120** [comment]
Thanks for your support!

According to the screenshots you provided, the locks are in the Playground/missions. The locks here are deliberately designed because of the needs of the mission.

The Lab in the Playground provides free experimentation and have no lock at all.

**Comment by nytschgeusen** [comment]
Ok, I have understood your intention. Perhaps you could hide (instead lock) all unused features of an experiment within the playground, if they don’t play a role in the specific context. This could be more clear for the user.

**Comment by jerryjee120** [comment]
Yes, you are right! We will fix it in the next update.

Thanks for your great advice. 
Any suggestions are welcome!
